#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo -e '\e[0;32m[HOOKS: commit-msg] commitlint 进行中\e[0m'

npx --no-install commitlint --edit $1

echo -e '\e[0;32m[HOOKS: commit-msg] commitlint 校验通过\e[0m'
